# Fonts
font_family      Liga SF Mono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0
disable_ligatures never

# Cursor
cursor_shape      underline
shell_integration no-cursor

# Scrollback
scrollback_lines 5000
scrollback_indicator_opacity 0.3

# Window
window_padding_width 3

# Performance
sync_to_monitor no

# Bell
enable_audio_bell no

# Advanced
wayland_enable_ime no

include current-theme.conf
